version: "3"

services:
  bookstore-api:
    image: bookstore-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: "172.18.0.1"
      DB_NAME: bookstore
      DB_USERNAME: root
      DB_PASSWORD: 123456
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - /app/node_modules
      - ./:/usr/src/app
  redis:
    image: redis
    ports:
      - "6379:6379"
